name: pop_syn
channels:
  - conda-forge
dependencies:
  - astropy=5.2
  - black=22.10.0
  - corner=2.2.1
  - cudatoolkit=11.6 # If you are a OSX user comment out this package.
  - f2c=20210323183018
  - ffmpeg=5.1.2
  - graphviz=6.0.2
  - healpy=1.16.1
  - ipykernel=6.19.3
  - julia=1.8.3 # If you are a OSX-arm64 user this package is not available.
  - jupyter=1.0.0
  - libtiff=4.5.0
  - matplotlib=3.6.2
  - nb_conda=2.2.1
  - ninja=1.11.0
  - numba=0.56.4
  - numpy=1.23.5
  - olefile=0.46
  - orjson=3.8.3
  - pandas=1.5.2
  - pillow=9.2.0
  - pip=22.3.1
  - pre-commit=2.20.0
  - pyinstrument=4.4.0
  - pytest=7.2.0
  - pytest-cov=4.0.0
  - pytest-runner=6.0.0
  - python=3.10.8
  - pytorch=1.12.1
  - pyyaml=6.0
  - recommonmark=0.7.1
  - scipy=1.9.3
  - sphinx=5.3.0
  - tensorboard=2.11.0
  - tensorboardx=2.5
  - termcolor=2.1.1
  - torchvision=0.13.0
  - zstd=1.5.2
  - pip:
      - julia
      - pydeps
      - pygedm --global-option=build_ext --global-option="-I${CONDA_PREFIX}/include:/usr/local/include"

