name: pop_syn_new
channels:
  - conda-forge
dependencies:
  - astropy=5.3.1
  - black=23.7.0
  - corner=2.2.2
#  - cudatoolkit=11.6.0  # If you are a OSX user comment out this package.
  - f2c=20210323183018  # Do we use this?
  - graphviz=8.1.0  # Do we use this?
  - healpy=1.16.2
#  - ipykernel=6.19.3  # Automatically installed with jupyter lab
#  - julia=1.9.2  # If you are a OSX-arm64 user this package is not available.
#  - jupyter=1.0.0  # no longer advised to use this
  - jupyterlab=4.0.3
#  - libtiff=4.5.0  # installed with other package
  - matplotlib=3.7.1
#  - nb_conda=2.2.1  # this is causing issues and not longer the advised way to run different kernels
  - ninja=1.11.1  # Do we use this?
  - notebook=7.0.1  # use this to execute old school jupyter notebooks
  - numba=0.57.1
  - numpy=1.24.4
  - olefile=0.46  # Do we use this?
  - orjson=3.9.2
  - pandas=2.0.3
#  - pillow=9.2.0  # installed with other package
  - pip=23.2.1
  - pre-commit=3.3.3
  - pyinstrument=4.5.1
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - pytest-runner=6.0.0
  - python=3.11.4
  - pytorch=2.0.0  # THIS IS THE ISSUE: not clear if we can update this from pytorch=1.12.1
#  - pyyaml=6.0  # installed with other package
  - recommonmark=0.7.1  # Do we use this?
  - scipy=1.11.1
  - sphinx=7.1.1
  - tensorboard=2.13.0
  - tensorboardx=2.6.2
  - termcolor=2.1.1
  - torchvision=0.15.2
#  - zstd=1.5.2  # installed with other package
  - pip:
      - julia
      - pydeps
      - pygedm --global-option=build_ext --global-option="-I${CONDA_PREFIX}/include:/usr/local/include"