#!/usr/bin/evn python3
# -*- coding: utf-8 -*-
"""
Generation of the HTCondor scripts.

We generate all the scripts needed to sequentially run chunks of simulations using the Dagman tool of HTCondor.
Each job will run each chunk of simulations for different set of initial parameters.

Note that this script needs the output from the `parameter_sweeper.py` script.
As specified with the command line argument --output_dir_htcondor the submit files for each job, a
dagman file and a wrapper are saved in this path.


    Authors:
        Celsa Pardo (pardo @ csic.es)


Copyright (c) MAGNESIA (ICE-CSIC) 2020

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import argparse
import pathlib

import numpy as np


def generate_job_submit(
    path_output: pathlib.Path,
    index: int,
    path_arguments_chunk: str,
    full_path_dagman: pathlib.Path,
):
    """
    Create all the submit files.

    Args:

        path_output (pathlib.Path): Output directory for the submit file.
        index (int) : Index of the submit file.
        path_arguments_chunk (pathlib.Path): Path to a txt file with the list of arguments.

    Returns:

        Nothing.
    """
    # Path where each submit file will be saved.
    path_submit = pathlib.Path().joinpath(
        path_output, "job" + str(index) + ".submit"
    )
    # Writing the HTCondor submit file, specifying the relevant arguments, output/error paths and queue structure.
    with open(path_submit, "w") as f:
        f.write("universe        = vanilla \n")
        f.write(
            "executable      = " + str(full_path_dagman) + "/wrapper.sh \n"
        )
        f.write("arguments       = $(arg1) $(arg2) \n")
        f.write("output          = $(arg1)/out.txt \n")
        f.write("error           = $(arg1)/error.txt \n")
        f.write("Queue arg1 arg2 from " + str(path_arguments_chunk) + "\n")
        f.close()


def dagman_generator(args):

    full_path_dagman = pathlib.Path().joinpath(
        "/data/magnesia/common", args.output_dir_htcondor
    )

    simulation_output_path = pathlib.Path(args.output_dir_simulation)

    # Reading the txt generated by the parameter_sweeper.py that contains the simulation arguments.
    simulation_arguments = np.genfromtxt(
        pathlib.Path().joinpath(
            simulation_output_path, "simulation_arguments.txt"
        ),
        dtype=str,
    )

    # Total number of simulations as specified when calling the parameter_sweeper.py script.
    n_sim = len(simulation_arguments)

    # We want HTCondor to run a maximum of ´chunk_size´ simulations within a single job.
    if n_sim % args.chunk_size == 0:
        n_jobs = int(n_sim / args.chunk_size)
    else:
        n_jobs = int(n_sim / args.chunk_size) + 1

    output_path = pathlib.Path(args.output_dir_htcondor)

    output_path.mkdir(parents=True, exist_ok=True)

    # Create the dagjob file using Dagman's PARENT CHILD capability to launch a range of jobs sequentially.
    parent_child_array = [
        "PARENT " + str(i + 1) + " CHILD " + str(i + 2)
        for i in range(n_jobs - 1)
    ]

    jobs_array = [
        "JOB "
        + str(i + 1)
        + " "
        + str(full_path_dagman)
        + "/job"
        + str(i + 1)
        + ".submit"
        for i in range(n_jobs)
    ]

    dagjob_array = jobs_array + parent_child_array

    path_dagman = pathlib.Path().joinpath(output_path, "dagjob.dag")

    np.savetxt(path_dagman, dagjob_array, fmt="%s")

    # Create the ´wrapper.sh´.
    path_wrapper = pathlib.Path().joinpath(output_path, "wrapper.sh")

    with open(path_wrapper, "w") as f:
        f.write("#!/bin/bash \n")
        f.write("\n")
        f.write("conda init bash\n")
        f.write(
            "source /data/magnesia/software/anaconda3/etc/profile.d/conda.sh\n"
        )
        f.write(
            "conda activate /data/magnesia/software/anaconda3/envs/pop_syn\n"
        )
        f.write("date\n")
        f.write(
            "python /data/magnesia/software/MAGNESIA_population_synthesis/examples/simulator/simulate_population_dyn.py --output_dir $1 --parameter_override $2\n"
        )
        f.write("date\n")
        f.close()

    # Looping through the number of jobs to create each submit file.
    for j in range(n_jobs):
        submit_path = pathlib.Path().joinpath(output_path)

        submit_path.mkdir(parents=True, exist_ok=True)

        arguments_chunk = simulation_arguments[
            j * args.chunk_size : (j + 1) * args.chunk_size
        ]

        path_arguments_chunk = pathlib.Path().joinpath(
            submit_path, "arguments" + str(j + 1) + ".txt"
        )

        np.savetxt(path_arguments_chunk, arguments_chunk, fmt="%s")

        generate_job_submit(
            submit_path,
            j + 1,
            str(full_path_dagman) + "/arguments" + str(j + 1) + ".txt",
            full_path_dagman,
        )


if __name__ == "__main__":
    args = argparse.ArgumentParser(description="HTCondor parameter")

    args.add_argument(
        "--output_dir_htcondor",
        nargs="?",
        type=str,
        default="output_dagman",
        help="Path to the directory where the files generated in this script will be saved.",
    )

    args.add_argument(
        "--output_dir_simulation",
        nargs="?",
        type=str,
        default="output/test",
        help="Path to the directory where the folders created with the parameter_sweeper.py are.",
    )

    args.add_argument(
        "--chunk_size",
        nargs="?",
        type=int,
        default=150,
        help="Number of parameters per job.",
    )

    args = args.parse_args()

    dagman_generator(args)
