#!/usr/bin/evn python3
# -*- coding: utf-8 -*-
"""
Generation of the HTCondor scripts.

We generate all the scripts needed to run the whole set of simulations in chunks using HTCondor.
Each job will run each chunk of simulations for a different set of initial parameters.

Note that this script needs the output from the `parameter_sweeper.py` script.
As specified with the command line argument --output_dir_htcondor the submit files for each job, the
arguments.txt and a wrapper are saved in this path.


    Authors:
        Celsa Pardo (pardo @ csic.es)


Copyright (c) MAGNESIA (ICE-CSIC) 2020

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import argparse
import pathlib

import numpy as np


def generate_job_submit(path_output: pathlib.Path):
    """
    Create all the submit files.

    Args:

        path_output (pathlib.Path): Output directory for the submit file.

    Returns:

        Nothing.
    """
    # Path where each submit file will be saved.
    path_submit = pathlib.Path().joinpath(path_output, "job.submit")
    path_arguments_chunk = str(path_output) + "/arguments.txt"
    # Writing the HTCondor submit file, specifying the relevant arguments, output/error paths and queue structure.

    with open(path_submit, "w") as f:
        f.write("universe        = vanilla \n")
        f.write("executable      = " + str(path_output) + "/wrapper.sh \n")
        f.write(
            "output          = " + str(path_output) + "/$(ProcId)-out.txt \n"
        )
        f.write(
            "error           = " + str(path_output) + "/$(ProcId)-error.txt \n"
        )
        f.write("Queue arguments from " + str(path_arguments_chunk) + "\n")
        f.close()


def generate_wrapper(path_wrapper):

    """
    Create all the wrapper files.

    Args:

        path_wrapper (pathlib.Path): Output directory for the wrapper file.

    Returns:

        Nothing.
    """

    # Writing the `wrapper.sh` file where we loop over the lines of the `arguments<i>.txt` file.

    with open(path_wrapper, "w") as f:

        f.write(
            "#!/bin/bash  \n"
            " \n"
            "conda init bash \n"
            "source /data/magnesia/software/anaconda3/etc/profile.d/conda.sh \n"
            "conda activate /data/magnesia/software/anaconda3/envs/pop_syn \n"
            "date \n"
            "filename=$1 \n"
            "while read line; do \n"
            "# Reading each line. \n"
            "myarr[$index]=$line \n"
            "#Extract each element from the lines. \n"
            "a=(${myarr[$index]}) \n"
            "python /data/magnesia/software/MAGNESIA_population_synthesis/examples/simulator/simulate_population_dyn.py --output_dir ${a[0]} --parameter_override ${a[1]} \n"
            "done < $filename \n"
            "date\n"
        )

        f.close()


def submit_generator(args):

    common_path = "/data/magnesia/common/"

    simulation_output_path = pathlib.Path(args.output_dir_simulation)

    output_htcondor_path = pathlib.Path(args.output_dir_htcondor)

    output_htcondor_path.mkdir(parents=True, exist_ok=True)

    # Reading the txt generated by the parameter_sweeper.py that contains the simulation arguments.
    simulation_arguments = np.genfromtxt(
        pathlib.Path().joinpath(
            simulation_output_path, "simulation_arguments.txt"
        ),
        dtype=str,
    )

    n_sim = len(simulation_arguments)

    # How many jobs we want to run per each week.
    if n_sim % args.n_submit == 0:
        n_submit_folder = int(n_sim / args.n_submit)
    else:
        n_submit_folder = int(n_sim / args.n_submit) + 1

    for i in range(n_submit_folder):

        # We create one folder per each submit file.
        submit_folder_path = pathlib.Path().joinpath(
            output_htcondor_path, "submit" + str(i)
        )
        submit_folder_path.mkdir(parents=True, exist_ok=True)

        # Taking the chunk of simulations that we want to run each week.
        sim_week = simulation_arguments[
            i * args.n_submit : (i + 1) * args.n_submit
        ]

        n_submit = len(sim_week)

        # Number of simulations per each job.
        if n_submit % args.chunk_size == 0:
            n_jobs = int(n_submit / args.chunk_size)
        else:
            n_jobs = int(n_submit / args.chunk_size) + 1

        # Create the ´wrapper.sh´.
        path_wrapper = pathlib.Path().joinpath(
            submit_folder_path, "wrapper.sh"
        )
        generate_wrapper(path_wrapper)

        # Create the ´.submit ´ file.
        generate_job_submit(submit_folder_path)

        list_arguments = []

        # Looping through the number of jobs to create each `argument<i>.txt` file.
        for j in range(n_jobs):

            arguments_chunk = sim_week[
                j * args.chunk_size : (j + 1) * args.chunk_size
            ]

            path_arguments_chunk = pathlib.Path().joinpath(
                common_path,
                str(submit_folder_path) + "/arguments" + str(j + 1) + ".txt",
            )

            np.savetxt(path_arguments_chunk, arguments_chunk, fmt="%s")
            # List of all the path of each `argument<i>.txt` file
            list_arguments.append(path_arguments_chunk)

        path_arguments = pathlib.Path().joinpath(
            submit_folder_path, "arguments.txt"
        )

        np.savetxt(path_arguments, list_arguments, fmt="%s")


if __name__ == "__main__":

    args = argparse.ArgumentParser(description="HTCondor parameter")

    args.add_argument(
        "--output_dir_htcondor",
        nargs="?",
        type=str,
        default="output_htcondor",
        help="Path to the directory where the files generated in this script will be saved.",
    )

    args.add_argument(
        "--output_dir_simulation",
        nargs="?",
        type=str,
        default="output/test",
        help="Path to the directory where the folders created with the parameter_sweeper.py are.",
    )

    args.add_argument(
        "--chunk_size",
        nargs="?",
        type=int,
        default=150,
        help="Number of parameters per job.",
    )

    args.add_argument(
        "--n_submit",
        nargs="?",
        type=int,
        default=False,
        help="Number of jobs per submit file.",
    )

    args = args.parse_args()

    submit_generator(args)
