#!/usr/bin/evn python3
# -*- coding: utf-8 -*-
"""
Generation of the HTCondor scripts.

This script generates all the scripts needed to sequentially run chunks of simulations, i.e., a group of simulations for a given set of parameters, in a single job using Dagman tool of HTCondor.
Note that this script needs the output from the `parameter_sweeper.py` script.
In the argument --output_dir_htcondor we specify where it will be saved all the submit files for each job and a
dagman file for sequentially running each of those jobs.


    Authors:
        Celsa Pardo (pardo @ csic.es)


Copyright (c) MAGNESIA (ICE-CSIC) 2020

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import argparse
import pathlib

import numpy as np


def generate_job_submit(
    path_output: pathlib.Path, index: int, path_arguments_chunk: str
):
    """
    Create all the submit files.

    Args:

        path_output (pathlib.Path): Output directory for the submit file.
        index (int) : index of the submit file.
        path_arguments_chunk (pathlib.Path): Path to a txt file with the list of arguments.

    Returns:

        Nothing.
    """

    path_submit = pathlib.Path().joinpath(
        path_output, "job" + str(index) + ".submit"
    )

    with open(path_submit, "w") as f:
        f.write("universe        = vanilla \n")
        f.write("executable      = wrapper.sh \n")
        f.write("arguments       = $(arg1) $(arg2) \n")
        f.write("output          = $(arg1)/out.txt \n")
        f.write("error           = $(arg1)/error.txt \n")
        f.write("Queue arg1 arg2 from " + str(path_arguments_chunk) + "\n")
        f.close()


def main(args):
    simulation_output_path = pathlib.Path(args.output_dir_simulation)

    # Reading the txt generated by the parameter_sweeper.py where the simulation arguments are.
    simulation_arguments = np.genfromtxt(
        pathlib.Path().joinpath(
            simulation_output_path, "simulation_arguments.txt"
        ),
        dtype=str,
    )

    # Total number of simulations that we want to run especified when calling the parameter_sweeper.py script.
    n_sim = len(simulation_arguments)

    # We want that HTCondor runs as maximum ´chunk_size´ simulations within 1 job.
    if n_sim % args.chunk_size == 0:
        n_jobs = int(n_sim / args.chunk_size)
    else:
        n_jobs = int(n_sim / args.chunk_size) + 1

    output_path = pathlib.Path(args.output_dir_htcondor)

    output_path.mkdir(parents=True, exist_ok=True)

    # Create the dagjob file.
    parent_child_array = [
        "PARENT " + str(i + 1) + " CHILD " + str(i + 2)
        for i in range(n_jobs - 1)
    ]

    jobs_array = [
        "JOB " + str(index + 1) + " job" + str(index + 1) + ".submit"
        for index in range(n_jobs)
    ]

    parent_child_array = jobs_array + parent_child_array

    parent_child_array = np.array(parent_child_array)

    path_dagman = pathlib.Path().joinpath(output_path, "dagjob.dag")

    np.savetxt(path_dagman, parent_child_array, fmt="%s")

    # Create the ´wrapper.sh´.
    path_wrapper = pathlib.Path().joinpath(output_path, "wrapper.sh")

    with open(path_wrapper, "w") as f:
        f.write("#!/bin/bash \n")
        f.write("\n")
        f.write("export PATH=/data/magnesia/software/anaconda3/bin:$PATH\n")
        f.write("conda init bash\n")
        f.write(
            "source /data/magnesia/software/anaconda3/etc/profile.d/conda.sh\n"
        )
        f.write(
            "conda activate /data/magnesia/software/anaconda3/envs/pop_syn\n"
        )
        f.write("date\n")
        f.write(
            "python /data/magnesia/software/MAGNESIA_population_synthesis/examples/simulator/simulate_population_dyn.py --output_dir $1 --parameter_override $2\n"
        )
        f.write("date\n")
        f.close()

    # Looping through the number of jobs to create each submit file.
    for index in range(n_jobs):
        submit_path = pathlib.Path().joinpath(output_path)

        submit_path.mkdir(parents=True, exist_ok=True)

        arguments_chunk = simulation_arguments[
            index * args.chunk_size : (index + 1) * args.chunk_size
        ]

        path_arguments_chunk = pathlib.Path().joinpath(
            submit_path, "arguments" + str(index + 1) + ".txt"
        )

        np.savetxt(path_arguments_chunk, arguments_chunk, fmt="%s")

        generate_job_submit(
            submit_path, index + 1, "arguments" + str(index + 1) + ".txt"
        )


if __name__ == "__main__":
    args = argparse.ArgumentParser(description="HTCondor parameter")

    args.add_argument(
        "--output_dir_htcondor",
        nargs="?",
        type=str,
        default="output_dagman",
        help="Path to the directory where the files generated in this script will be saved.",
    )

    args.add_argument(
        "--output_dir_simulation",
        nargs="?",
        type=str,
        default="output/test",
        help="Path to the directory where the folders created with the parameter_sweeper.py are.",
    )

    args.add_argument(
        "--chunk_size",
        nargs="?",
        type=int,
        default=150,
        help="Number of parameters per each job.",
    )

    args = args.parse_args()

    main(args)
