name: github action pipeline
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/pop_syn
          key: conda-${{ hashFiles('environment.yaml') }}
        id: cache
      - name: Install environment
        run: conda env create --file environment.yaml --force
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Always install pip dependencies
        run: conda env update -n pop_syn --file environment.yaml
      - name: Install package in development mode
        shell: bash -l {0}
        run: python setup.py develop
#      - name: Run all tests
#        shell: bash -l {0}
#        run: pytest